// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern "C" void AESL_WRAP_makePatches_ShadowQuilt_fromEdges (
long long apexZ0,
int stop,
int ppl,
char leftRight,
volatile void* n_patches,
volatile void* GDarray,
volatile void* GDn_points,
volatile void* patches_superpoints_0,
volatile void* patches_superpoints_1,
volatile void* patches_superpoints_2,
volatile void* patches_superpoints_3,
volatile void* patches_superpoints_4,
volatile void* patches_superpoints_5,
volatile void* patches_superpoints_6,
volatile void* patches_superpoints_7,
volatile void* patches_superpoints_8,
volatile void* patches_superpoints_9,
volatile void* patches_superpoints_10,
volatile void* patches_superpoints_11,
volatile void* patches_superpoints_12,
volatile void* patches_superpoints_13,
volatile void* patches_superpoints_14,
volatile void* patches_superpoints_15,
volatile void* patches_superpoints_16,
volatile void* patches_superpoints_17,
volatile void* patches_superpoints_18,
volatile void* patches_superpoints_19,
volatile void* patches_superpoints_20,
volatile void* patches_superpoints_21,
volatile void* patches_superpoints_22,
volatile void* patches_superpoints_23,
volatile void* patches_superpoints_24,
volatile void* patches_superpoints_25,
volatile void* patches_superpoints_26,
volatile void* patches_superpoints_27,
volatile void* patches_superpoints_28,
volatile void* patches_superpoints_29,
volatile void* patches_superpoints_30,
volatile void* patches_superpoints_31,
volatile void* patches_parameters_0,
volatile void* patches_parameters_1,
volatile void* patches_parameters_2,
volatile void* patches_parameters_3,
volatile void* patches_parameters_4);
