#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("stop", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("ppl", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("leftRight", 1, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("n_patches", 8, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("n_patches_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("GDarray_address0", 10, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("GDarray_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("GDarray_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("GDarray_d0", 64, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("GDarray_q0", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("GDarray_address1", 10, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("GDarray_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("GDarray_we1", 1, hls_out, 4, "ap_memory", "MemPortWE2", 1),
	Port_Property("GDarray_d1", 64, hls_out, 4, "ap_memory", "MemPortDIN2", 1),
	Port_Property("GDarray_q1", 64, hls_in, 4, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("GDn_points_address0", 3, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("GDn_points_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("GDn_points_we0", 1, hls_out, 5, "ap_memory", "mem_we", 1),
	Port_Property("GDn_points_d0", 32, hls_out, 5, "ap_memory", "mem_din", 1),
	Port_Property("GDn_points_q0", 32, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("GDn_points_address1", 3, hls_out, 5, "ap_memory", "MemPortADDR2", 1),
	Port_Property("GDn_points_ce1", 1, hls_out, 5, "ap_memory", "MemPortCE2", 1),
	Port_Property("GDn_points_we1", 1, hls_out, 5, "ap_memory", "MemPortWE2", 1),
	Port_Property("GDn_points_d1", 32, hls_out, 5, "ap_memory", "MemPortDIN2", 1),
	Port_Property("GDn_points_q1", 32, hls_in, 5, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("patches_superpoints_address0", 3, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("patches_superpoints_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("patches_superpoints_we0", 1, hls_out, 6, "ap_memory", "mem_we", 1),
	Port_Property("patches_superpoints_d0", 1024, hls_out, 6, "ap_memory", "mem_din", 1),
	Port_Property("patches_superpoints_q0", 1024, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("patches_superpoints_address1", 3, hls_out, 6, "ap_memory", "MemPortADDR2", 1),
	Port_Property("patches_superpoints_ce1", 1, hls_out, 6, "ap_memory", "MemPortCE2", 1),
	Port_Property("patches_superpoints_we1", 1, hls_out, 6, "ap_memory", "MemPortWE2", 1),
	Port_Property("patches_superpoints_d1", 1024, hls_out, 6, "ap_memory", "MemPortDIN2", 1),
	Port_Property("patches_superpoints_q1", 1024, hls_in, 6, "ap_memory", "MemPortDOUT2", 1),
};
const char* HLS_Design_Meta::dut_name = "makePatches_ShadowQuilt_fromEdges";
